version: 2
jobs:
  build:
    docker:
      - image: node:9
    steps:
      - checkout
      - run:
          name: Install Typescript and TSLint
          command: npm i -g typescript tslint
      - run:
          name: Install packages
          command: npm i
      - run:
          name: Lint
          command: npm run lint